//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowBridge
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public decimal PRICE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ACTIVE { get; set; }
    }
}
